#' @title Calculate marginal likelihood by thermodynamic integration (LTI)
#' @description  Calculate the marginal likelihood from a logfile generated by \code{\link{jive_mcmc}} with thermodynamic integration
#' @param mcmc.log the output file of a \code{\link{jive_mcmc}} run
#' @export
#' @author Theo Gaboriau and Simon Joly 
#' @examples 
#' ## Load test data
#' data(Anolis_traits)
#' data(Anolis_tree)
#' data(Anolis_map)
#' 
#' ## Run a MCMC chain with thermodynamic Integration
#' set.seed(300)
#' my.jive <- make_jive(Anolis_tree, Anolis_traits,  model.var="OU", model.mean="BM")
#' mcmc_jive(my.jive, log.file="my.jive_MCMC.log", ncat=10, sampling.freq=10, print.freq=100, ngen=5000, burnin=500)
#'  
#' ## import the results in R
#' logfile <- "my.jive_MCMC.log"
#' res <- read.csv(logfile, header = T, sep = "\t")
#'  
#' mlik <- marginal.lik(res)
#' mlik


marginal.lik <- function(mcmc.log) {

	if (!("Posterior" %in% colnames(mcmc.log))) stop('No \'Posterior\' column in the log file')
	if (!("temperature" %in% colnames(mcmc.log))) stop('No \'temperature\' column in the log file')

	# Get mean marginal likelihood for each temperature
	lik <- sapply(unique(mcmc.log$temperature), function(temp) mean(mcmc.log$Posterior[mcmc.log$temperature == temp], na.rm = T)) 

	if (length(lik)<=1) warning('Only one temerature for the thermodynamic integration')

	# The marginal likelihood
	lik.ti = 0
	# Calculate the intervals in temperature
	intervals <- unique(mcmc.log$temperature)[-1] - unique(mcmc.log$temperature)[-length(unique(mcmc.log$temperature))]
	# Estimate the integral
	for (i in 1:length(intervals)) {
	  lik.ti = lik.ti + ((lik[i]+lik[i+1])/2 * intervals[i])
	}

	return(lik.ti)

}

